service: cloud-factory-task
frameworkVersion: "2"

custom:
  region:
    dev: ap-south-1

  profile:
    dev: personal

  deploymentBucket:
    dev: rajan-test-bucket-mumbai

package:
  individually: true
  exclude:
    - package.json
    - node_modules/**
    - layer/nodejs/node_modules/**

plugins:
  - serverless-dotenv-plugin

layers:
  NodeModules:
    path: layer
    description: "Dependencies for lambdas"
    compatibleRuntimes:
      - nodejs14.x
    retain: false

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: ${self:custom.region.${self:provider.stage}}
  deploymentBucket: ${self:custom.deploymentBucket.${self:provider.stage}}
  profile: ${self:custom.profile.${self:provider.stage}}
  layers:
    - { Ref: NodeModulesLambdaLayer }

functions:
  - ${file(src/functions/covid/index.yml)}
  - ${file(src/functions/email/index.yml)}
